apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cicd-devops
  labels:
    app: k8s-cicd-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-cicd-devops
  template:
    metadata:
      labels:
        app: k8s-cicd-devops
    spec:
      containers:
        - name: k8s-cicd-devops
          image: gabrielnihi/k8s-cicd-devops:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: k8s-cicd-devops-config
            - secretRef:
                name: k8s-cicd-devops-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
